version: '2'
services:
  zookeeper:
    image: zookeeper:3.6
    hostname: zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      KAFKA_LISTENERS: "PLAINTEXT://:9092,SSL://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,SSL://localhost:9093"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "composition:1:1,ehr:1:1"
